@echo off
echo Stopper eksisterende server...
taskkill /f /im node.exe 2>nul
timeout /t 2 /nobreak > nul
echo Starter server på nytt...
cd /d "C:\Users\holge\Documents\Annet\mattilbud\middagstilbud-app\middagstilbud"
echo Starting Node.js server...
node rest/src/server.js
